In [3]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response = stats.ks_2samp(sample1, sample2)


In [4]:
sample1

array([0.24635655, 0.82356959, 0.67404423, 0.11124213, 0.76913883,
       0.91769684, 0.39282388, 0.82872976, 0.44515384, 0.77870414,
       0.63093834, 0.18560693, 0.6745147 , 0.06835445, 0.65891835,
       0.67970759, 0.78502832, 0.79205821, 0.80506347, 0.17023488,
       0.83088659, 0.39456112, 0.12874553, 0.1287039 , 0.3914397 ,
       0.1287233 , 0.09074349, 0.92388022, 0.20150552, 0.91806991,
       0.42163234, 0.32412601, 0.81043514, 0.8405128 , 0.0611034 ,
       0.40745611, 0.33536868, 0.77148108, 0.99444923, 0.74381802,
       0.80490033, 0.89575712, 0.23647338, 0.61191589, 0.18838212,
       0.90256371, 0.26492937, 0.00231484, 0.50873329, 0.4807622 ,
       0.75802496, 0.31019057, 0.78850716, 0.08557853, 0.04367872,
       0.82268662, 0.46573642, 0.09201879, 0.34305779, 0.96415602,
       0.36701069, 0.50391773, 0.04403776, 0.18990222, 0.56521796,
       0.58139931, 0.26516846, 0.16060307, 0.97243328, 0.79906031,
       0.75045403, 0.65594268, 0.24839604, 0.54296715, 0.37047

In [5]:
sample2

array([-0.20507734, -2.49511504,  1.05764419,  1.14348501, -0.35146188,
       -0.27801106,  0.33642628, -0.20309153,  0.89736377,  1.78164026,
       -0.69793618,  0.05662431,  0.56941848, -1.15196245,  2.34401572,
        0.03602281, -1.83000754, -0.49569029,  0.15162961, -0.63905204,
        1.81717299,  1.79612548, -0.99572205,  1.40108495,  0.94037112,
        0.35108844, -0.69925573, -1.26315676, -0.65792035,  0.97874264,
       -0.25297336,  1.37376458, -2.5175339 ,  0.03228511,  0.2552341 ,
        0.20875742, -0.78075098,  1.64803581, -1.39427086,  1.15543849,
       -2.58343003, -0.57094163,  0.18317518, -2.06073918,  0.48803322,
        0.45902622, -0.75791523, -0.88104013,  0.13110096,  1.40054503,
       -0.34701003,  0.20917237, -0.21181729,  0.47389491,  0.39451352,
        0.52660625, -0.16422053,  1.07915327, -1.34630539,  1.50516015,
        0.53134199,  0.46500489, -0.59396853, -0.31241908, -1.17112334,
       -1.02440003,  0.39580379, -0.01667009, -0.52379745,  1.34

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/config/workspace/artifact/12072022__15202022/data_ingestion/dataset/train.csv")

In [8]:
drop_column_name=[]
for column_name,missing_percentage in zip((df.isna().sum()/df.shape[0]).index, (df.isna().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)
    if (missing_percentage>0.3):
        drop_column_name.append(column_name)

class 0.0
aa_000 0.0
ab_000 77.00172711571676
ac_000 5.837651122625216
ad_000 25.602763385146805
ae_000 4.324697754749568
af_000 4.324697754749568
ag_000 1.0466321243523318
ag_001 1.0466321243523318
ag_002 1.0466321243523318
ag_003 1.0466321243523318
ag_004 1.0466321243523318
ag_005 1.0466321243523318
ag_006 1.0466321243523318
ag_007 1.0466321243523318
ag_008 1.0466321243523318
ag_009 1.0466321243523318
ah_000 1.1053540587219344
ai_000 1.063903281519862
aj_000 1.063903281519862
ak_000 7.60621761658031
al_000 1.1053540587219344
am_0 1.063903281519862
an_000 1.1053540587219344
ao_000 0.9844559585492229
ap_000 1.1053540587219344
aq_000 0.9844559585492229
ar_000 4.690846286701209
as_000 1.063903281519862
at_000 1.063903281519862
au_000 1.063903281519862
av_000 4.328151986183074
ax_000 4.328151986183074
ay_000 1.0466321243523318
ay_001 1.0466321243523318
ay_002 1.0466321243523318
ay_003 1.0466321243523318
ay_004 1.0466321243523318
ay_005 1.0466321243523318
ay_006 1.0466321243523318
ay_007 1

In [9]:
(df.isna().sum()/df.shape[0]).values,(df.isna().sum()/df.shape[0]).index

(array([0.        , 0.        , 0.77001727, 0.05837651, 0.25602763,
        0.04324698, 0.04324698, 0.01046632, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01046632, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01105354, 0.01063903, 0.01063903,
        0.07606218, 0.01105354, 0.01063903, 0.01105354, 0.00984456,
        0.01105354, 0.00984456, 0.04690846, 0.01063903, 0.01063903,
        0.01063903, 0.04328152, 0.04328152, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01046632, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01046632, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01046632, 0.01046632, 0.01046632,
        0.01046632, 0.01046632, 0.01046632, 0.01070812, 0.01070812,
        0.01070812, 0.01070812, 0.01070812, 0.01070812, 0.01070812,
        0.01070812, 0.01070812, 0.01070812, 0.01105354, 0.04697755,
        0.04697755, 0.04331606, 0.04324698, 0.01105354, 0.01105354,
        0.00984456, 0.00984456, 0.38262522, 0.45

In [10]:
null_report = df.isna().sum()/df.shape[0]

In [11]:
null_report[null_report>0.3]

ab_000    0.770017
bk_000    0.382625
bl_000    0.452297
bm_000    0.655751
bn_000    0.728636
bo_000    0.766010
bp_000    0.788601
bq_000    0.805769
br_000    0.814715
cr_000    0.770017
dtype: float64